import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { HeaderMenu } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Brown AI Safety Team",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className="min-h-full flex flex-col">
        <MantineProvider defaultColorScheme="auto">
          <HeaderMenu />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
